### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by jakwuh** [jakearchibald/big-web-quiz#23]
Hi, Jake!

Just want to say you thanks for open-sourcing this code and also writing articles on how you made the Big Web Quiz.

I wonder, how did you manage to write such a complex app without having some unit/e2e/integration tests? To be honest it looks to me as something unbelievable.

**Comment by jakearchibald** [comment]
Glad the code is useful! It was hacked together pretty quickly.

> how did you manage to write such a complex app without having some unit/e2e/integration tests? To be honest it looks to me as something unbelievable.

Urrrrr we just kinda crossed our fingers and hoped. Not something I'd recommend doing! But the app isn't all that complicated, there are only a few states.
